---
filter_out_less_than_percentage: 90
filter_out_non_certified: true
filter_out_already_downloaded: true
comments:
    analyze: true # Turning this off isn't even supported right now.
    quality: high # or low
    results_to_analyze: 15
download_directory: ~/Torrents