---
filter_out_less_than_percentage: 95
filter_out_non_certified: 1
filter_out_already_downloaded: 1
comments:
    analyze: false
    quality: high # or low
    results_to_analyze: 15
download_directory: tmp/torrents