---
filter_out_less_than_percentage: 90
filter_out_non_certified_fresh: true
filter_out_already_downloaded: false
comments:
    analyze: true
    quality: high # or low
    num_to_analyze: 9
    minimum_seeds: 1500
download_directory: ~/Torrents
